### ISSUE TITLE
Can't connect to kube-api using master IP

### ISSUE THREAD

**Issue by ngocluanbka** [ngocluanbka/IoT#2]
In Master Node, If i run kubelet with command
`sudo kubelet --api-servers=http://127.0.0.1:8080  --address=0.0.0.0 --enable-debugging-handlers=true --config=/etc/kubernetes/manifests --allow-privileged=False --v=2 --cluster-domain=cluster.local`
every thing is ok.

But if i change --api-servers like that (192.168.1.15 is master IP)
`sudo kubelet --api-servers=http://192.168.1.15:8080  --address=0.0.0.0 --enable-debugging-handlers=true --config=/etc/kubernetes/manifests --allow-privileged=False --v=2 --cluster-domain=cluster.local`

I got an error
`pkg/kubelet/config/apiserver.go:43: Failed to list *api.Pod: Get http://192.168.1.15:8080/api/v1/pods?fieldSelector=spec.nodeName%3Diot01&resourceVersion=0: dial tcp 192.168.1.15:8080: getsockopt: connection refused
`

I have checked the port that api-server served. This is the result
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      -               
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:10249         0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:2379          0.0.0.0:*               LISTEN      -               


```

Is anyone have idea for this issue ?

**Comment by haqduong** [comment]
You should bind --insecure-bind-address, it's for 8080 which is insecure port.

**Comment by ngocluanbka** [comment]
@haqduong i have already done that. Here is my config for Kube-api
```
apiserver:
  image: gcr.io/google_containers/kube-apiserver-amd64:v1.4.0-beta.8
  net: host
  command: ["/usr/local/bin/kube-apiserver","--etcd-servers=http://127.0.0.1:2379", "--service-cluster-ip-range=172.17.17.1/24", " --insecure-bind-address=http://0.0.0.0", "--v=2"]
```

**Comment by haqduong** [comment]
@ngocluanbka  check my config:
```
apiserver:
  image: gcr.io/google_containers/kube-apiserver-amd64:v1.4.0-beta.8
  net: host
  command: ["/usr/local/bin/kube-apiserver","--etcd-servers=http://127.0.0.1:2379", "--service-cluster-ip-range=172.17.17.1/24", "--bind-address=0.0.0.0", "--insecure-bind-address=0.0.0.0", "--v=2"]

```

and kubelet arguments:

`sudo kubelet --api-servers=http://192.168.122.144:8080  --address=0.0.0.0 --enable-debugging-handlers=true --config=/etc/kubernetes/manifests --allow-privileged=False --v=2 --cluster-domain=cluster.local
`
